=== julitamajerx/xml-zadania/faktura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Faktura">
        <xs:complexType>
            <xs:sequence>
                <!--NAGŁÓWEK-->
                <xs:element name="Naglowek">
                    <xs:complexType>
                        <xs:sequence>
                             <!--Miejsce Wystawienia-->
                            <xs:element name="MiejsceWystawienia" type="xs:string"/>
                            <!--Data-->
                            <xs:element name="Data">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Wystawienia" type="xs:date"/>
                                        <xs:element name="Sprzedazy" type="xs:date"/>
                                        <xs:element name="Operacji" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <!--Platność-->
                            <xs:element name="Platnosc">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Termin">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:positiveInteger">
                                                        <xs:attribute name="jednostka" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="RachunekBankowy">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="kodKraju" type="xs:string" use="required" />
                                                        <xs:attribute name="bank" type="xs:string" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Rodzaj" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--STRONY TRANSAKCJI-->
                <xs:element name="StronyTransakcji">
                    <xs:complexType>
                        <xs:sequence>
                               <xs:element name="Sprzedawca" type="TypPodmiot"/>
                               <xs:element name="Nabywca" type="TypPodmiot"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--POZYCJE-->
                <xs:element name="Pozycje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Pozycja" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nazwa" type="xs:string"/>
                                        <xs:element name="JednostkaMiary" type="xs:string"/>
                                        <xs:element name="Ilosc" type="xs:decimal"/>
                                        <xs:element name="Cena">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="TypKwota">
                                                        <xs:attribute name="waluta" type="xs:string" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Netto" type="TypKwota"/>
                                        <xs:element name="Vat">
                                             <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="TypKwota">
                                                        <xs:attribute name="stawka" type="xs:string" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Brutto" type="TypKwota"/>
                                    </xs:sequence>
                                    <xs:attribute name="lp" type="xs:positiveInteger" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- PODSUMOWANIE-->
                 <xs:element name="Podsumowanie">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Netto" type="TypKwota"/>
                            <xs:element name="Vat">
                                <xs:complexType>
                                     <xs:simpleContent>
                                            <xs:extension base="TypKwota">
                                                <xs:attribute name="stawka" type="xs:string" use="required" />
                                            </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Brutto" type="TypKwota"/>
                        </xs:sequence>
                    </xs:complexType>
                 </xs:element>
            </xs:sequence>
            <xs:attribute name="numer" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="TypKwota">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TypPodmiot">
        <xs:sequence>
            <xs:element name="Nazwa" type="xs:string"/>
            <xs:element name="Nip" type="xs:string"/>
            <xs:element name="Adres">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Ulica" type="xs:string"/>
                        <xs:element name="Lokal" type="xs:string" minOccurs="0"/>
                        <xs:element name="Kod" type="xs:string"/>
                        <xs:element name="Miejscowosc" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== julitamajerx/xml-zadania/faktura.xml
<?xml version="1.0" encoding="UTF-8"?>
<Faktura numer="1/FVS/2026" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="faktura.xsd">
    <Naglowek>
        <MiejsceWystawienia>Warszawa</MiejsceWystawienia>
        <Data>
            <Wystawienia>2026-02-13</Wystawienia>
            <Sprzedazy>2026-02-13</Sprzedazy>
            <Operacji>2026-02-13</Operacji>
        </Data>
        <Platnosc>
            <Termin jednostka="dni">14</Termin>
            <RachunekBankowy kodKraju="PL" bank="mBank">24900000050000460083168772</RachunekBankowy>
            <Rodzaj>Przelew</Rodzaj>
        </Platnosc>
    </Naglowek>
    <StronyTransakcji>
        <Sprzedawca>
            <Nazwa>Piekarnia "Upiekło Ci Się"</Nazwa>
            <Nip>1234567890</Nip>
            <Adres>
                <Ulica>Kowalska 5</Ulica>
                <Lokal>10</Lokal>
                <Kod>05-100</Kod>
                <Miejscowosc>Nowy Dwór Mazowiecki</Miejscowosc>
            </Adres>
        </Sprzedawca>

        <Nabywca>
            <Nazwa>ABC Info Jan Nowak</Nazwa>
            <Nip>0987654321</Nip>
            <Adres>
                <Ulica>Górnicza 90</Ulica>
                <Lokal>43</Lokal>
                <Kod>02-142</Kod>
                <Miejscowosc>Warszawa</Miejscowosc>
            </Adres>
        </Nabywca>
    </StronyTransakcji>
    <Pozycje>
        <Pozycja lp="1">
            <Nazwa>Ciastko truskawkowe 4-pak</Nazwa>
            <JednostkaMiary>szt.</JednostkaMiary>
            <Ilosc>5</Ilosc>
            <Cena waluta="PLN">30.00</Cena>
            <Netto>150</Netto>
            <Vat stawka="8%">12</Vat>
            <Brutto>162</Brutto>
        </Pozycja>
        <Pozycja lp="2">
            <Nazwa>Ciastko malinowe 4-pak</Nazwa>
            <JednostkaMiary>szt.</JednostkaMiary>
            <Ilosc>5</Ilosc>
            <Cena waluta="PLN">30.00</Cena>
            <Netto>150</Netto>
            <Vat stawka="8%">12</Vat>
            <Brutto>162</Brutto>
        </Pozycja>

    </Pozycje>
    <Podsumowanie>
        <Netto>150</Netto>
        <Vat stawka="8%">12</Vat>
        <Brutto>162</Brutto>
    </Podsumowanie>
</Faktura>
